name: Deploy Infra
defaults:
  run:
    working-directory: ./Cloud_Infrastruct_Automation/network_for-each
on:
  pull_request:
    branches:
      - main
    paths:
      - 'Cloud_Infrastruct_Automation/network_for-each/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  Checkov:
    name: 'Check TF Vuls'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Atualizado para v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          # O Checkov precisa do caminho relativo Ã  raiz do repo
          directory: ./Cloud_Infrastruct_Automation/network_for-each
          framework: terraform
        continue-on-error: true

  Apply:
    name: 'Apply Changes'
    runs-on: ubuntu-latest
    environment: lab
    needs: Checkov
    defaults:
      run:
        shell: bash
        # Repetindo o working-directory para garantir o contexto neste job
        working-directory: ./Cloud_Infrastruct_Automation/network_for-each

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply --auto-approve
