name: Deploy VPC

  #defaults:
  #  run:
  #    working-directory: ./Cloud_Infrastruct_Automation/network_for-each
on:
  push:
    branches:
      - main
        #   paths-ignore:
        #     - '.github/**'
    paths:
      - 'Cloud_Infrastruct_Automation/network_for-each/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  destroy:
    name: 'Destroy VPC'
    runs-on: ubuntu-latest
    # runs-on: [shared, self-hosted]
    environment: lab

    defaults:
      run:
        shell: bash
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: ./Cloud_Infrastruct_Automation/network_for-each  

      - name: Show Terraform plan
        run: terraform plan -destroy
        working-directory: ./Cloud_Infrastruct_Automation/network_for-each  

        
      - name: Destroy resource jobs
        id: destroy
        run: terraform destroy --auto-approve
        working-directory: ./Cloud_Infrastruct_Automation/network_for-each  
